var hoteis = [];
var servicos = [];

var hotel = new Object();
var servico = new Object();


hoteis[1] = [hotel.nome = "Caiçara Hotel" , hotel.id_tipo = "1", hotel.endereco = "Praça dos Expedicionários, 7, Santos, Estado de São Paulo 11065-500, Brasil", hotel.telefone = "(13) 3284-6798", hotel.website = "caicarahotel.com.br", hotel.email = "reserva@caicarahotel.com.br", hotel.id_servico = "1", hotel.classificao = "", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[1] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[2] = [hotel.nome = "Caravelas Hotel" , hotel.id_tipo = "1", hotel.endereco = "Avenida Senador Pinheiro Machado 1023, Santos, Estado de São Paulo 11075-971, Brasil", hotel.telefone = "(13) 3237-2645", hotel.website = "hotelcaravelas.com.br", hotel.email = "hotelcaravelas@vivaz.com.br", hotel.id_servico = "2", hotel.classificao = "2", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[2] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[3] = [hotel.nome = "Carina Flat" , hotel.id_tipo = "1", hotel.endereco = "Rua Ministro Joao Mendes 271, Santos, Estado de São Paulo 11040-261, Brasil", hotel.telefone = "(13) 3278-2000", hotel.website = "grupomendes.com.br/carinaflat.com.br", hotel.email = "carinaflat@grupomendes.com.br", hotel.id_servico = "3", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[3] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[4] = [hotel.nome = "Casarão Hotel" , hotel.id_tipo = "1", hotel.endereco = "Av Almirante Cochrane 21 | Embaré, Santos, Estado de São Paulo 11040-001, Brasil", hotel.telefone = "(13) 3231-8684", hotel.website = "casaraohotel.com", hotel.email = "Hotel Atlânticohotel", hotel.id_servico = "4", classificao = "", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[4] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[5] = [hotel.nome = "Cosmopolitan Praia Flat" , hotel.id_tipo = "1", hotel.endereco = "Rua Bahia 174, Santos, Estado de São Paulo 11060-451, Brasil", hotel.telefone = "(13) 2102-9493", hotel.website = "cosmopolitanpraiaflat.com.br", hotel.email = "reservas@cosmopolitanpraiaflat.com e comercial@cosmopolitanpraiaflat.com", hotel.id_servico = "5", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[5] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "1", servico.academia = "1", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[6] = [hotel.nome = "Gonzaga Flat" , hotel.id_tipo = "1", hotel.endereco = "Rua Jorge Tibirica, 41 | Gonzaga, Santos, Estado de São Paulo 11055-250, Brasil", hotel.telefone = "(13) 2102-5800", hotel.website = "gonzagaflat.tur.br", hotel.email = "reservas@gonzagaflat.tur.br e gerencia@gonzagaflat.tur.br", hotel.id_servico = "6", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[6] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[7] = [hotel.nome = "Mercure" , hotel.id_tipo = "1", hotel.endereco = "Avenida Washington Luis 565 | Boqueirao, Santos, Estado de São Paulo 11055-001, Brasil", hotel.telefone = "(13) 30361013", hotel.website = "https://www.accorhotels.com/pt/hotel-6314-mercure-santos-hotel/index.shtml", hotel.email = "h6314-re@accor.com.br", hotel.id_servico = "7", hotel.classificao = "4", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[7] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "1", servico.academia = "1", servico.spa = "1", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[8] = [hotel.nome = "Monte Serrat Confort Hotel" , hotel.id_tipo = "1", hotel.endereco = "Rua Bittencourt 130, Santos, Estado de São Paulo 11013-300, Brasil", hotel.telefone = "(13) 3232-6624", hotel.website = "www.monteserrathotel.com.br", hotel.email = "reservas@monteserrathotel.com.br", hotel.id_servico = "8", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[8] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "1", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[9] = [hotel.nome = "Hotel Atlântico", hotel.id_tipo = "1", hotel.endereco = "Avenida Presidente Wilson, 01, Santos, Estado de São Paulo 11065-200, Brasil", hotel.telefone = "(13) 3289-4500", hotel.website = "atlantico-hotel.com.br", hotel.email = "flavia@atlantico-hotel.com.br", hotel.id_servico = "9", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[9] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[10] = [hotel.nome = "Hotel Atlantico Inn", hotel.id_tipo = "1", hotel.endereco = "Rua Jorge Tibirica 04 | Gonzaga, Santos, Estado de São Paulo 11055-250, Brasil", hotel.telefone = "(13) 3289-4700", hotel.website = "atlanticoinn.com.br", hotel.email = "reservas@atlanticoinn.com.br  atlanticoinn@atlanticoinn.com.br", hotel.id_servico = "10", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[10] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "1", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[11] = [hotel.nome = "Hotel Avenida Palace", hotel.id_tipo = "1", hotel.endereco = "Avenida Presidente Wilson, 10 | Gonzaga, Santos, Estado de São Paulo 11065-200, Brasil", hotel.telefone = "(13) 3289-3555", hotel.website = "avenidapalace.com.br", hotel.email = "reserva@avenidapalace.com.br", hotel.id_servico = "11", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[11] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[12] = [hotel.nome = "Hotel e Pousada Cantinho da Praia", hotel.id_tipo = "2", hotel.endereco = "Avenida Doutor Bernardino de Campos n 637, Santos, Estado de São Paulo 11065-001, Brasil", hotel.telefone = "(13) 3288-1174", hotel.website = "www.hotelcantinhodapraia.com.br", hotel.email = "atendimento@pousadacantinhodapraia.com.br", hotel.id_servico = "12", hotel.classificao = "", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[12] = [servico.wifi_quartos = "2", servico.wifi_lobby = "2", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[13] = [hotel.nome = "Hotel Fenícia", hotel.id_tipo = "1", hotel.endereco = "Av Presidente Wilson, 184 - José Menino - (11065201) - Santos, São Paulo", hotel.telefone = "(13) 3237-1955", hotel.website = "feniciapraiahotel.com.br", hotel.email = "feniciapraiahotel@uol.com.br  feniciapraiahotel@gmail.com", hotel.id_servico = "13", hotel.classificao = "", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[13] = [servico.wifi_quartos = "2", servico.wifi_lobby = "2", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[14] = [hotel.nome = "Hotel Independência", hotel.id_tipo = "1", hotel.endereco = "Av Marechal Floriano Peixoto, 206 | Gonzaga, Santos, Estado de São Paulo 11060-302, Brasil", hotel.telefone = "(13) 3237-6224", hotel.website = "independenciahotel.com.br", hotel.email = "contato@hotelindependencia.com.br", hotel.id_servico = "14", hotel.classificao = "", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[14] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "1", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[15] = [hotel.nome = "Hotel Natal", hotel.id_tipo = "1", hotel.endereco = "Avenida Marechal Floriano Peixoto 104, Santos, Estado de São Paulo 11060-300, Brasil", hotel.telefone = "(13) 3284-2732", hotel.website = "hotelnatal.com.br", hotel.email = "hotelnatal@hotelnatal.com.br", hotel.id_servico = "15", hotel.classificao = "2", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[15] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[16] = [hotel.nome = "Hotel Paulista Praia", hotel.id_tipo = "1", hotel.endereco = "Av Presidente Wilson, 134, José Menino, Santos, Estado de São Paulo 11065-201, Brasil", hotel.telefone = "(13) 3237-0198", hotel.website = "paulistapraia.com.br", hotel.email = "paulistapraia@ig.com.br", hotel.id_servico = "16", hotel.classificao = "", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[16] = [servico.wifi_quartos = "2", servico.wifi_lobby = "2", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[17] = [hotel.nome = "Hotel Praiano", hotel.id_tipo = "1", hotel.endereco = "Av. Barão de Penedo, 39 - José Menino, Santos, Estado de São Paulo 11065-651, Brasil", hotel.telefone = "(13) 3237-4033", hotel.website = "hotelpraiano.com.br", hotel.email = "reservas@hotelpraiano.com.br", hotel.id_servico = "17", hotel.classificao = "", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[17] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "1", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[18] = [hotel.nome = "Panorama Hotel", hotel.id_tipo = "1", hotel.endereco = "Rua Euclides da Cunha 15, Santos, Estado de São Paulo 11065-901, Brasil", hotel.telefone = "(13) 3208-6400", hotel.website = "mplaza.com.br", hotel.email = "reservas@mendesplaza.com.br", hotel.id_servico = "18", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[18] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "1" ];

hoteis[19] = [hotel.nome = "Parque Balneário", hotel.id_tipo = "1", hotel.endereco = "Av Ana Costa 555 | Praia do Gonzaga, Santos, Estado de São Paulo 11060-003, Brasil", hotel.telefone = "(13) 3285-6900", hotel.website = "parquebalneario.com.br", hotel.email = "reservas@parquebalneario.com.br", hotel.id_servico = "19", hotel.classificao = "4", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[19] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "2", servico.academia = "1", servico.spa = "2", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "2" ];

hoteis[20] = [hotel.nome = "Hotel Ritz", hotel.id_tipo = "1", hotel.endereco = "Avenida Marechal Deodoro, 24, Santos, Estado de São Paulo 11060-400, Brasil", hotel.telefone = "(13) 3284-1171", hotel.website = "hotelritz.com.br", hotel.email = "reservas@hotelritz.com.br", hotel.id_servico = "20", hotel.classificao = "2 estrelas", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[20] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "2", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[21] = [hotel.nome = "Hotel Atlantico Golden", hotel.id_tipo = "1", hotel.endereco = "Rua Jorge Tibirica 40, Santos, Estado de São Paulo 11055-250, Brasil", hotel.telefone = "(13) 3289-4600", hotel.website = "atlanticogolden.com.br", hotel.email = "atlanticogolden@atlanticogolden.com.br  reservas@atlanticogolden.com.br", hotel.id_servico = "21", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[21] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "1", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "2" , servico.pet_permitidos = "2" ];

hoteis[22] = [hotel.nome = "Hotel Ibis", hotel.id_tipo = "1", hotel.endereco = "Avenida Vicente de Carvalho 50 | Boqueirao, Santos, Estado de São Paulo 11045-500, Brasil", hotel.telefone = "(13) 2127-1660", hotel.website = "www.ibishotel.com", hotel.email = "h5530-re@accor.com.br", hotel.id_servico = "22", hotel.classificao = "3 estrelas", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[22] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "2", servico.estacionamento = "1", servico.academia = "2", servico.spa = "2", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "1" ];

hoteis[23] = [hotel.nome = "Plaza Hotel", hotel.id_tipo = "1", hotel.endereco = "Avenida Marechal Floriano Peixoto, 42, Santos, Estado de São Paulo 11060-300, Brasil", hotel.telefone = "(13) 3208-6400", hotel.website = "mplaza.com.br", hotel.email = "reservas@mendesplaza.com.br", hotel.id_servico = "23", hotel.classificao = "4 estrelas", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[23] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "2", servico.academia = "1", servico.spa = "1", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "1" ];

hoteis[24] = [hotel.nome = "Novotel", hotel.id_tipo = "1", hotel.endereco = "Av. Dona Ana Costa, 473, Santos, Estado de São Paulo 11060-003, Brasil", hotel.telefone = "(13) 3878-9700", hotel.website = "https://www.accorhotels.com/pt-br/hotel-8649-novotel-santos/index.shtml#origin=novotel", hotel.email = "h8649-re@accor.com.br", hotel.id_servico = "24", hotel.classificao = "4", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[24] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "1", servico.academia = "1", servico.spa = "1", servico.bar_no_hotel = "1", servico.restaurante = "1" , servico.pet_permitidos = "1" ];

hoteis[25] = [hotel.nome = "Comfort", hotel.id_tipo = "1", hotel.endereco = "Av. Rei Alberto I, 177 | Ponta da Praia, Santos, Estado de São Paulo 11030-381, Brasil", hotel.telefone = "(13) 2138-1100", hotel.website = "http://www.atlanticahotels.com.br/hotel/santos/comfort-hotel-santos", hotel.email = "", hotel.id_servico = "25", hotel.classificao = "3", hotel.id_cidade = "8", hotel.id_img = ""];
servicos[25] = [servico.wifi_quartos = "1", servico.wifi_lobby = "1", servico.psicina = "1", servico.estacionamento = "2", servico.academia = "1", servico.spa = "2", servico.bar_no_hotel = "2", servico.restaurante = "1" , servico.pet_permitidos = "2" ];
